languages:
  JavaScript: true
engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  fixme:
    enabled: false
  duplication:
    enabled: false
exclude_paths:
  - src/lib/*
  - src/test/*
  - dist/*
  - wikum/*
  - bower/*
  - *.md
  - *.mk
  - *.xml
  - *.json
  - Makefile
  - COPYING
