engines:
  eslint:
    enabled: true
  fixme:
    enabled: false
  duplication:
    enabled: false
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- src/lib/*
- src/test/*
- dist/*
- wikum/*
- bower/*
- *.md
- *.mk
- *.xml
- *.json
- Makefile
- COPYING
